apiVersion: v1
kind: Secret
metadata:
  name: horsecare-secrets
  namespace: horsecare
type: Opaque
data:
  pg-user: <REDACTED>
  pg-pass: <REDACTED>
  pg-db: <REDACTED>
  pgrst-jwt-secret: <REDACTED>
